---
- name: Tomcat deployment playbook
  hosts: tomcat-nodes       # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: root         # Update username for remote server
  vars:
    tomcat_ver: 8.5.70                          # Tomcat version to install
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: Aksa@1234                    # UI admin password
  roles:
    - tomcat

